### ISSUE TITLE
style_formats

### ISSUE THREAD

**Issue by mi32dogs** [loyals-online/silverstripe-tinymce4#1]
Hi, 
first of all thank you for this module.

I have a question, I’m implementing this and it is working fine so far the only problem I’m having is that I’m not able to set the style_formats.

I have tried it like I did with tinymce 3

$formats = array(
  array('title' => 'section', 'block' => 'section', 'wrapper' => true, 'merge_siblings' => false),
  array('title' => 'article', 'block' => 'article', 'wrapper' => true, 'merge_siblings' => false),
  array('title' => 'hgroup', 'block' => 'hgroup', 'wrapper' => true),
  array('title' => 'aside', 'block' => 'aside', 'wrapper' => true),
  array('title' => 'figure', 'block' => 'figure', 'wrapper' => true),
  array('title' => 'img-responsive', 'wrapper' => false),
);
CustomHtmlEditorConfig::get('cms')->setOption('style_formats',$formats);

And I tried an example from the tinymce website:
$formats =  array(
                array('title' => 'Headers',
                    'items' => array(
                        array('title' => 'h1', 'block' => 'h1'),
                        array('title' => 'h2', 'block' => 'h2'),
                        array('title' => 'h3', 'block' => 'h3'),
                        array('title' => 'h4', 'block' => 'h4'),
                        array('title' => 'h5', 'block' => 'h5'),
                        array('title' => 'h6', 'block' => 'h6')
                    )
                ),
                array('title' => 'Blocks',
                    'items' => array(
                        array('title' => 'p', 'block' => 'p'),
                        array('title' => 'div', 'block' => 'div'),
                        array('title' => 'pre', 'block' => 'pre')
                    )
                ),
                array('title' => 'Containers',
                    'items' => array(
                        array('title' => 'section', 'block' => 'section', 'wrapper' => true, 'merge_siblings' =>  false),
                        array('title' => 'article', 'block' => 'article', 'wrapper' => true, 'merge_siblings' =>  false),
                        array('title' => 'blockquote', 'block' => 'blockquote', 'wrapper' => true),
                        array('title' => 'hgroup', 'block' => 'hgroup', 'wrapper' => true),
                        array('title' => 'aside', 'block' => 'aside', 'wrapper' => true),
                        array('title' => 'figure', 'block' => 'figure', 'wrapper' => true)
                    )
                )
            );
CustomHtmlEditorConfig::get('cms')->setOption('style_formats',$formats);

I see on the graphic that you got it working so can you give me a pointer on what I’m doing wrong.

Thanks
Rob

**Comment by gavro** [comment]
Hi Rob,

It seems there are two issues which prevent you to use the style_formats call.

1 - It seems the enabled 'importcss' plugin can prevent the newly pushed styles. You could fix this by disabling importcss, e.g.:

```
CustomHtmlEditorConfig::get('cms')->disablePlugins('importcss');

$formats = array(
    array('title' => 'section', 'block' => 'section', 'wrapper' => true, 'merge_siblings' => false),
    array('title' => 'article', 'block' => 'article', 'wrapper' => true, 'merge_siblings' => false),
    array('title' => 'hgroup', 'block' => 'hgroup', 'wrapper' => true),
    array('title' => 'aside', 'block' => 'aside', 'wrapper' => true),
    array('title' => 'figure', 'block' => 'figure', 'wrapper' => true),
    array('title' => 'img-responsive', 'wrapper' => false),
);

CustomHtmlEditorConfig::get('cms')->setOption('style_formats', $formats);
```

2 - It seems that call (1) is not working when you do this for example in mysite/_config.php. tinymce4/_config.php is called _after_ mysite. Will have to figure out how to fix this (using `Before: 'mysite/*'` in _config/config.yml is not working. For now you could fix this by creating a dummy module like /zconfig/_config.php with your settings. Nasty, but it'll work until this gets fixed.

Thanks for finding this!

PS. The graphic is an older screenshot where all the default styles were enabled.

**Comment by mi32dogs** [comment]
Thanks, yes disabling the importcss did the job, working like a charm now
