### ISSUE TITLE
setOption('style_formats') not working

### ISSUE THREAD

**Issue by dpezer** [loyals-online/silverstripe-tinymce4#10]
I'm using latest SilverStripe 3.5.0 and I can't get style_formats to append in editor:

my code:

```
$formats = array(
  array('title' => 'Big text', 'selector' => 'p', 'classes' => 'lead'),
  array('title' => 'Set responsive table', 'selector' => 'table', 'classes' => 'table')
);
```

`CustomHtmlEditorConfig::get('cms')->setOption('style_formats', $formats);`

**Comment by gavro** [comment]
@darianno could you check if the solution in [this closed issue](https://github.com/loyals-online/silverstripe-tinymce4/issues/1) solves your problem?

**Comment by dpezer** [comment]
I've tried CustomHtmlEditorConfig::get('cms')->disablePlugins('importcss') but it does not work.

**Comment by dpezer** [comment]
trick with creating dummy module /zconfig/_config.php worked.
