### ISSUE TITLE
compatabilty with 3.2

### ISSUE THREAD

**Issue by mi32dogs** [loyals-online/silverstripe-tinymce4#2]
Hi, i have trying to get it to work on the 3.2.0-beta2 version, it will open a tinyMCE4 editor window but it has none of the configuration that i have set in the _config.php file.
any idea why?

Thanks 
Rob

**Comment by groundnation** [comment]
Bump - support with 3.2 would be great

**Comment by gavro** [comment]
Check, since 3.2 has already gone stable this is a must-have. Will bump this in my prio list.

**Comment by groundnation** [comment]
Fantastic - can't imagine a SilverStripe site without this module

**Comment by gavro** [comment]
@mi32dogs @groundnation dev-master + branch 1.1 have been updated (1.0 branch = 3.1 compat). Could you let me know if this fixes all issues? I'll push a new tag (1.1.0) when this is ready & usable.

**Comment by groundnation** [comment]
Hi Gavro - yep, all good – thanks for the update.

**Comment by gavro** [comment]
@groundnation Just pushed a fix for the editor, they've changed the link-popup functionality. Merged back, now working again.

**Comment by groundnation** [comment]
Yep - got it, all good. Thanks.

**Comment by mi32dogs** [comment]
Great, thank you
