### ISSUE TITLE
Second CustomHTMLEditorField is not saving

### ISSUE THREAD

**Issue by mi32dogs** [loyals-online/silverstripe-tinymce4#3]
Hi, i'm not sure if it is just me but if i have 2 CustomHTMLEditorField on the page than the second one is not being saved, also if i type in the second editor field the publish button stay's grayed out.

is this just me or does somebody have the same problem?

**Comment by gavro** [comment]
Hm, I can't seem to reproduce this error. Which branch are you using? And could you post your code somewhere (at least $db + getCMSFields()) ?

**Comment by mi32dogs** [comment]
finally, found the problem it was the 'forced_root_block' that i had added it worked fine in SS 3.1 but seems to be a problem in SS 3.2 so i removed it
